name: hello-world

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: clone do repo
        uses: actions/checkout@v3

      - name: print
        run: echo "Nosso workflow rodando ao realizar um push/pr"
